package com.jkpr.chinesecheckers.server.message;

/**
 * The {@code GenMessage} class represents a message of type {@link MessageType#GEN}.
 * It is used to carry generic messages, typically generated by the server,
 * in a serialized format to be sent to the client.
 *
 * <p>This class stores the message content as a string and provides a method to
 * serialize the content into the appropriate string format.</p>
 */
public class GenMessage extends Message {
    private final String content;

    /**
     * Constructs a new {@code GenMessage} with the specified content.
     *
     * @param content the content of the message
     */
    public GenMessage(String content) {
        super(MessageType.GEN);
        this.content = content;
    }

    /**
     * Gets the content of this {@code GenMessage}.
     *
     * @return the content of this message
     */
    public String getContent() {
        return content;
    }

    /**
     * Serializes the {@code GenMessage} into a string format.
     * The format follows the convention: "GEN <content>".
     *
     * @return the string representation of this message
     */
    @Override
    public String serialize() {
        return MessageType.GEN + " " + content;
    }
}
